// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfa6pvzQ98cpME1HhoRlxAh9e3tQx9KnM',
    appId: '1:473927393143:web:4706671fffadedfe534b72',
    messagingSenderId: '473927393143',
    projectId: 'dr-ai-e14d1',
    authDomain: 'dr-ai-e14d1.firebaseapp.com',
    storageBucket: 'dr-ai-e14d1.appspot.com',
    measurementId: 'G-H78GBTFH8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeoCC8wUy2hrY8H4Ioim2t9x5coPMe9JY',
    appId: '1:473927393143:android:ee63ca9253b44cd5534b72',
    messagingSenderId: '473927393143',
    projectId: 'dr-ai-e14d1',
    storageBucket: 'dr-ai-e14d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzpVQJCExBqE8sVOE9j4JohssxugZgFyg',
    appId: '1:473927393143:ios:60725f9ed6d68ec2534b72',
    messagingSenderId: '473927393143',
    projectId: 'dr-ai-e14d1',
    storageBucket: 'dr-ai-e14d1.appspot.com',
    iosBundleId: 'com.example.drAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzpVQJCExBqE8sVOE9j4JohssxugZgFyg',
    appId: '1:473927393143:ios:48faab1f42f933ac534b72',
    messagingSenderId: '473927393143',
    projectId: 'dr-ai-e14d1',
    storageBucket: 'dr-ai-e14d1.appspot.com',
    iosBundleId: 'com.example.drAi.RunnerTests',
  );
}
